/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-09 05:10:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686118631163L));
    _jspx_dependants.put("jar:file:/C:/Users/bharg/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjectRestaurant/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"Start your development with FoodHut landing page.\">\r\n");
      out.write("    <meta name=\"author\" content=\"Devcrud\">\r\n");
      out.write("    <title>FoodHut | Free Bootstrap 4.3.x template</title>\r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <!-- font icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href='");
      if (_jspx_meth_spring_005furl_005f2(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href='");
      if (_jspx_meth_spring_005furl_005f3(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap + FoodHut main styles -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/foodhut.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"40\" id=\"home\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"custom-navbar navbar navbar-expand-lg navbar-dark fixed-top\" data-spy=\"affix\" data-offset-top=\"10\">\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#home\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#about\">About</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#gallary\">Gallary</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#book-table\">Book-Table</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <a class=\"navbar-brand m-auto\" href=\"#\">\r\n");
      out.write("                <img src=\"assets/imgs/logo.svg\" class=\"brand-img\" alt=\"\">\r\n");
      out.write("                <span class=\"brand-txt\">Food Hut</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#blog\">Blog<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#testmonial\">Reviews</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#contact\">Contact Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"components.html\" class=\"btn btn-primary ml-xl-4\">Components</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <header id=\"home\" class=\"header\">\r\n");
      out.write("        <div class=\"overlay text-white text-center\">\r\n");
      out.write("            <h1 class=\"display-2 font-weight-bold my-3\">Food Hut</h1>\r\n");
      out.write("            <h2 class=\"display-4 mb-5\">Always fresh &amp; Delightful</h2>\r\n");
      out.write("            <a class=\"btn btn-lg btn-primary\" href=\"#gallary\">View Our gallary</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!--  About Section  -->\r\n");
      out.write("    <div id=\"about\" class=\"container-fluid wow fadeIn\" id=\"about\"data-wow-duration=\"1.5s\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6 has-img-bg\"></div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-sm-8 py-5 my-5\">\r\n");
      out.write("                        <h2 class=\"mb-4\">About Us</h2>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, quisquam accusantium nostrum modi, nemo, officia veritatis ipsum facere maxime assumenda voluptatum enim! Labore maiores placeat impedit, vero sed est voluptas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita alias dicta autem, maiores doloremque quo perferendis, ut obcaecati harum, <br><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum necessitatibus iste,\r\n");
      out.write("                        nulla recusandae porro minus nemo eaque cum repudiandae quidem voluptate magnam voluptatum? <br>Nobis, saepe sapiente omnis qui eligendi pariatur. quis voluptas. Assumenda facere adipisci quaerat. Illum doloremque quae omnis vitae.</p>\r\n");
      out.write("                        <p><b>Lonsectetur adipisicing elit. Blanditiis aspernatur, ratione dolore vero asperiores explicabo.</b></p>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos ab itaque modi, reprehenderit fugit soluta, molestias optio repellat incidunt iure sed deserunt nemo magnam rem explicabo vitae. Cum, nostrum, quidem.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--  gallary Section  -->\r\n");
      out.write("    <div id=\"gallary\" class=\"text-center bg-dark text-light has-height-md middle-items wow fadeIn\">\r\n");
      out.write("        <h2 class=\"section-title\">OUR MENU</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"gallary row\">\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-1.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-2.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-3.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-4.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-5.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-6.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-7.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-8.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-9.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-10.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-11.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6 col-lg-3 gallary-item wow fadeIn\">\r\n");
      out.write("            <img src=\"assets/imgs/gallary-12.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"gallary-img\">\r\n");
      out.write("            <a href=\"#\" class=\"gallary-overlay\">\r\n");
      out.write("                <i class=\"gallary-icon ti-plus\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- book a table Section  -->\r\n");
      out.write("    <div class=\"container-fluid has-bg-overlay text-center text-light has-height-lg middle-items\" id=\"book-table\">\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            <h2 class=\"section-title mb-5\">BOOK A TABLE</h2>\r\n");
      out.write("            <div class=\"row mb-5\">\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 col-xs-12 my-2\">\r\n");
      out.write("                    <input type=\"email\" id=\"booktable\" class=\"form-control form-control-lg custom-form-control\" placeholder=\"EMAIL\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 col-xs-12 my-2\">\r\n");
      out.write("                    <input type=\"number\" id=\"booktable\" class=\"form-control form-control-lg custom-form-control\" placeholder=\"NUMBER OF GUESTS\" max=\"20\" min=\"0\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 col-xs-12 my-2\">\r\n");
      out.write("                    <input type=\"time\" id=\"booktable\" class=\"form-control form-control-lg custom-form-control\" placeholder=\"EMAIL\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 col-xs-12 my-2\">\r\n");
      out.write("                    <input type=\"date\" id=\"booktable\" class=\"form-control form-control-lg custom-form-control\" placeholder=\"12/12/12\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-lg btn-primary\" id=\"rounded-btn\">FIND TABLE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- BLOG Section  -->\r\n");
      out.write("    <div id=\"blog\" class=\"container-fluid bg-dark text-light py-5 text-center wow fadeIn\">\r\n");
      out.write("        <h2 class=\"section-title py-5\">EVENTS AT THE FOOD HUT</h2>\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-sm-7 col-md-4 mb-5\">\r\n");
      out.write("                <ul class=\"nav nav-pills nav-justified mb-3\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link active\" id=\"pills-home-tab\" data-toggle=\"pill\" href=\"#foods\" role=\"tab\" aria-controls=\"pills-home\" aria-selected=\"true\">Foods</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" id=\"pills-profile-tab\" data-toggle=\"pill\" href=\"#juices\" role=\"tab\" aria-controls=\"pills-profile\" aria-selected=\"false\">Juices</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tab-content\" id=\"pills-tabContent\">\r\n");
      out.write("            <div class=\"tab-pane fade show active\" id=\"foods\" role=\"tabpanel\" aria-labelledby=\"pills-home-tab\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"card bg-transparent border my-3 my-md-0\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-1.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$5</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Reiciendis Laborum </h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"card bg-transparent border my-3 my-md-0\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-2.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$12</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Adipisci Totam</h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"card bg-transparent border my-3 my-md-0\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-3.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$8</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Dicta Deserunt</h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tab-pane fade\" id=\"juices\" role=\"tabpanel\" aria-labelledby=\"pills-profile-tab\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                        <div class=\"card bg-transparent border\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-4.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$15</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Consectetur Adipisicing Elit</h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                        <div class=\"card bg-transparent border\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-5.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$29</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Ullam Laboriosam</h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                        <div class=\"card bg-transparent border\">\r\n");
      out.write("                            <img src=\"assets/imgs/blog-6.jpg\" alt=\"template by DevCRID http://www.devcrud.com/\" class=\"rounded-0 card-img-top mg-responsive\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h1 class=\"text-center mb-4\"><a href=\"#\" class=\"badge badge-primary\">$3</a></h1>\r\n");
      out.write("                                <h4 class=\"pt20 pb20\">Fugit Ipsam</h4>\r\n");
      out.write("                                <p class=\"text-white\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- REVIEWS Section  -->\r\n");
      out.write("    <div id=\"testmonial\" class=\"container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items\">\r\n");
      out.write("        <h2 class=\"section-title my-5 text-center\">REVIEWS</h2>\r\n");
      out.write("        <div class=\"row mt-3 mb-5\">\r\n");
      out.write("            <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                <div class=\"testmonial-card\">\r\n");
      out.write("                    <h3 class=\"testmonial-title\">John Doe</h3>\r\n");
      out.write("                    <h6 class=\"testmonial-subtitle\">Web Designer</h6>\r\n");
      out.write("                    <div class=\"testmonial-body\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum nobis eligendi, quaerat accusamus ipsum sequi dignissimos consequuntur blanditiis natus. Aperiam!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                <div class=\"testmonial-card\">\r\n");
      out.write("                    <h3 class=\"testmonial-title\">Steve Thomas</h3>\r\n");
      out.write("                    <h6 class=\"testmonial-subtitle\">UX/UI Designer</h6>\r\n");
      out.write("                    <div class=\"testmonial-body\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum minus obcaecati cum eligendi perferendis magni dolorum ipsum magnam, sunt reiciendis natus. Aperiam!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 my-3 my-md-0\">\r\n");
      out.write("                <div class=\"testmonial-card\">\r\n");
      out.write("                    <h3 class=\"testmonial-title\">Miranda Joy</h3>\r\n");
      out.write("                    <h6 class=\"testmonial-subtitle\">Graphic Designer</h6>\r\n");
      out.write("                    <div class=\"testmonial-body\">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nam. Earum nobis eligendi, dignissimos consequuntur blanditiis natus. Aperiam!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CONTACT Section  -->\r\n");
      out.write("    <div id=\"contact\" class=\"container-fluid bg-dark text-light border-top wow fadeIn\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 px-0\">\r\n");
      out.write("                <div id=\"map\" style=\"width: 100%; height: 100%; min-height: 400px\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 px-5 has-height-lg middle-items\">\r\n");
      out.write("                <h3>FIND US</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, laboriosam doloremque odio delectus, sunt magnam laborum impedit molestiae, magni quae ipsum, ullam eos! Alias suscipit impedit et, adipisci illo quam.</p>\r\n");
      out.write("                <div class=\"text-muted\">\r\n");
      out.write("                    <p><span class=\"ti-location-pin pr-3\"></span> 12345 Fake ST NoWhere, AB Country</p>\r\n");
      out.write("                    <p><span class=\"ti-support pr-3\"></span> (123) 456-7890</p>\r\n");
      out.write("                    <p><span class=\"ti-email pr-3\"></span>info@website.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- page footer  -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark text-light has-height-md middle-items border-top text-center wow fadeIn\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <h3>EMAIL US</h3>\r\n");
      out.write("                <P class=\"text-muted\">info@website.com</P>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <h3>CALL US</h3>\r\n");
      out.write("                <P class=\"text-muted\">(123) 456-7890</P>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <h3>FIND US</h3>\r\n");
      out.write("                <P class=\"text-muted\">12345 Fake ST NoWhere AB Country</P>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"bg-dark text-light text-center border-top wow fadeIn\">\r\n");
      out.write("        <p class=\"mb-0 py-3 text-muted small\">&copy; Copyright <script>document.write(new Date().getFullYear())</script> Made with <i class=\"ti-heart text-danger\"></i> By <a href=\"http://devcrud.com\">DevCRUD</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end of page footer -->\r\n");
      out.write("\r\n");
      out.write("	<!-- core  -->\r\n");
      out.write("    <script src=\"assets/vendors/jquery/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <script src=\"assets/vendors/bootstrap/bootstrap.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- bootstrap affix -->\r\n");
      out.write("    <script src=\"assets/vendors/bootstrap/bootstrap.affix.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- wow.js -->\r\n");
      out.write("    <script src=\"assets/vendors/wow/wow.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- google maps -->\r\n");
      out.write("    <script async defer src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCtme10pzgKSPeJVJrG1O3tjR6lk98o4w8&callback=initMap\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- FoodHut js -->\r\n");
      out.write("    <script src=\"assets/js/foodhut.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_spring_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(15,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/assets/vendors/themify-icons/css/themify-icons.css");
      // /WEB-INF/views/index.jsp(15,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("mainCss");
      int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
      if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_spring_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f1_reused = false;
    try {
      _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(16,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setValue("/assets/vendors/animate/animate.css");
      // /WEB-INF/views/index.jsp(16,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setVar("Main2Css");
      int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
      if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
      _jspx_th_spring_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_spring_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f2_reused = false;
    try {
      _jspx_th_spring_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f2.setParent(null);
      // /WEB-INF/views/index.jsp(19,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f2.setValue("/resources/static/assets/vendors/themify-icons/css/themify-icons.css");
      int _jspx_eval_spring_005furl_005f2 = _jspx_th_spring_005furl_005f2.doStartTag();
      if (_jspx_th_spring_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f2);
      _jspx_th_spring_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_spring_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f3_reused = false;
    try {
      _jspx_th_spring_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f3.setParent(null);
      // /WEB-INF/views/index.jsp(21,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f3.setValue("/resources/static/assets/vendors/animate/animate.css");
      int _jspx_eval_spring_005furl_005f3 = _jspx_th_spring_005furl_005f3.doStartTag();
      if (_jspx_th_spring_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f3);
      _jspx_th_spring_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f3_reused);
    }
    return false;
  }
}
